
default:
  name: "${AUX_SERVICE_RELEASE}"
  version: "${AUX_VERSION}"
  image: docker.io/polymatic/sidekiq-ui:6.4
  slug: "${AUX_PREFIX}"

variables:
- name: env
  data:
    REDIS_URL: "${SIDEKIQ_REDIS_URL}"
    SIDEKIQ_LICENSE_PRO: "${SIDEKIQ_LICENSE_PRO}"
    SIDEKIQ_LICENSE_ENTERPRISE: "${SIDEKIQ_LICENSE_ENTERPRISE}"

containers:
- name: app
  ports:
    - containerPort: 3030
  cpu:
    request: 100m
    limit: 1000m
  memory:
    request: 128Mi
    limit: 2Gi
  probe:
    path: /
    port: 3030

svc:
  ports:
  - name: http
    port: 80
    targetPort: 3030

conceal: ${ENDPOINT_DISABLE}

ingress:
- name: sidekiq-ui
  issuer: "${ENDPOINT_ISSUER}"
  cert: "${ENDPOINT_CERT}"
  annotations:
    external-dns.io/status: "${ENDPOINT_STATUS}"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-oauth2-proxy.authentication.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://proxy.${AUX_SERVICE_URL}/oauth2/start?rd=$escaped_request_uri"
  urls:
  - "${ENDPOINT_URL}"

hpa:
  min: ${POD_COUNT}
  max: ${POD_COUNT}
