
default:
  name: "${AUX_SERVICE_RELEASE}"
  version: "${AUX_VERSION}"
  image: docker.io/ankane/pghero:v2.8.1
  slug: "${AUX_PREFIX}"

variables:
- name: url
  data:
    DATABASE_URL: "${PGHERO_POSTGRESQL_URL}"

containers:
- name: app
  ports:
    - containerPort: 8080
  cpu:
    request: 20m
    limit: 100m
  memory:
    request: 288Mi
    limit: 512Mi
  probe:
    path: /health
    port: 8080

svc:
  ports:
  - name: http
    port: 80
    targetPort: 8080

conceal: ${ENDPOINT_DISABLE}

ingress:
- name: pghero
  issuer: "${ENDPOINT_ISSUER}"
  cert: "${ENDPOINT_CERT}"
  annotations:
    external-dns.io/status: "${ENDPOINT_STATUS}"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-oauth2-proxy.authentication.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://proxy.${AUX_SERVICE_URL}/oauth2/start?rd=$escaped_request_uri"
  urls:
  - "${ENDPOINT_URL}"

hpa:
  min: ${POD_COUNT}
  max: ${POD_COUNT}
